---
apiVersion: v1
appVersion: "0.1.1"
description: Annotation to series collect metadata workflow
name: annotation-collect-metadata-workflow
version: "0.0.0"
keywords:
- kaapanaworkflow
- kaapanaexperimental
